### ISSUE TITLE
Use a CI/CD system to automate building, testing and distribution

### ISSUE THREAD

**Issue by chippmann** [utopia-rise/kotlin-godot-wrapper#5]
**Describe the problem or limitation you are having in your project:**
Currently the project is not distributed to any public available repository. Each user has to build it from source by themselves.
Also all tests (which are not written yet -.- ) would have to be executed manually each time and relies on humans to be executed.

**Describe how this feature / enhancement will help you overcome this problem or limitation:**
The users don't have to clone the project anymore to be able to use it. Also i'ts more developer friendly as there are fewer manual steps in building and releasing. Which also reduces human errors.

**Show a mock up screenshots/video or a flow diagram explaining how your proposal will work:**
Commit -> Build on buildserver -> If failed (tests or build) mail to dev -> on tag: release to public repo when release notes are present

**Describe implementation detail for your proposal (in code), if possible:**
A CI/CD system should be used like (Travis, Jenkins, ...)

**If this enhancement will not be used often, can it be worked around with a few lines of code?:**
Yes but it's to cumbersome.

**Is there a reason why this should be in this project and not individually solved?:**
Yes because it makes the code better when combined with linting and makes the build process less errorprone.

Has to be done after #3 .

**Comment by piiertho** [comment]
Done with #12 
Will need to add test run to CI.

**Comment by chippmann** [comment]
Also we need to update it once i'm done with the kotlin compiler plugin. I will make an issue when i'm done with it.
